<!-- footer uses across all pages, amy -->
<footer class="footer" role="contentinfo">
  <div class="footer-container"
    style="border-top:1px solid #d8d8d8; padding:1rem; color:#555; display:flex; justify-content:space-between; text-align:center; align-items:center;">
    <p>&copy; <?php echo date('Y'); ?> SDLRC - Digital Careers for the Smart Future</p>
      <li><a href="mailto:info@companyname.com" style="color:#0645ad;">Contact Us</a></li>
      <li><a href="https://github.com/amywamy/COS10026_Group3_Part2" style="color:#0645ad;">GitHub Repository</a></li>
      <li><a href="https://sarahagate101.atlassian.net/jira/software/projects/SCRUM/boards/1" style="color:#0645ad;">Jira Page</a></li>
  </div>
  </footer>