<!-- footer uses across all pages -->
<footer class="footer" role="contentinfo">
<p>&copy; <?php echo date('Y'); ?>SDLRC - Digital Careers for the Smart Future</p>
<a href="mailto:info@companyname.com" style="color:#0645ad;">Contact Us</a>
<a href="https://github.com/amywamy/COS10026_Group3_Part2" style="color:#0645ad;">GitHub Repository</a>
<a href="https://sarahagate101.atlassian.net/jira/software/projects/SCRUM/boards/1" style="color:#0645ad;">Jira Page</a>
</footer>