<!-- header page, amy -->
<header class ="header" role="banner">
<link rel="stylesheet" href="styles/style.css">
<div class="logo-title">
   <a href="index.php" class="logo-link">
   <img src="/images_index/Website_logo.png" alt="SDLRC Logo" class="logo-icon">
   </a>
   <div class="text-group">
   <h1 class="site-name">SDLRC</h1>
   <p class="slogan">Digital Careers for the Smart Future</p>
   </div>
</div>
<?php include 'nav.inc'; ?>
</header>     