<!-- navigation of the header, amy -->
<nav class="navbar">
    <!-- Navigation links -->
    <ul class="nav-menu" id="navMenu">
      <li><a href="index.php" class="nav-link">Home</a></li>
      <li><a href="jobs.php" class="nav-link">Available Positions</a></li>
      <li><a href="apply.php" class="nav-link">Apply Now</a></li>
      <li><a href="about.php" class="nav-link">About Us</a></li>
      <li><a href="login.php" class="nav-link">Log In</a></li>
    </ul>
  </div>
</nav>